language: node_js

script: echo "No build needed"

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: demo.firstmakers.com
  skip_cleanup: true
  upload-dir: demo03
